spring:
  #名字很重要，方便feign通过Eureka拿到
  application:
    name: item-service
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
